### ISSUE TITLE
Cannot find aurelia bundler

### ISSUE THREAD

**Issue by adriatic** [stevies/aurelia-wizard-form-validation-example#2]
I would prefer not to fix anything, so you keep the full control of the state of this app :-)
```
C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example (master)
λ gulp watch
module.js:338
    throw err;
          ^
Error: Cannot find module 'aurelia-bundler'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\build\tasks\bundle.js:6:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by stevies** [comment]
When you ran "npm install" - did it work?  Do you have an aurelia-bundler directory under /node_modules?  Maybe you need to install gulp-bundler globally or something.

**Comment by adriatic** [comment]
Here is the "log" of ``npm install`` - there are a lot of errors related to ``node-gyp`` failing to find some VC++ component on my machine - I had several interactions with ``node-gyp`` developer, without a good solution (it has to do with the right to distribute this component).

As I was forced to accept the flashing of such "not important" error messages, it is possible that I missed something else 

```
C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example (master)
λ npm install
npm WARN package.json cbs-assurance-view-3@1.0.0 No license field.
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
/


> phantomjs@1.9.18 install C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\phantomjs
> node install.js

Download already available at C:\Users\Nikolaj\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Extracting zip contents
Removing C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\phantomjs\lib\phantom
Copying extracted folder C:\Users\Nikolaj\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip-extract-1442161621948\phantomjs-1.9.8-windows -> C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\phantomjs\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\phantomjs\lib\phantom\phantomjs.exe
|


> bufferutil@1.1.0 install C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild

|
C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil {git}

{lamb} if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bufferutil.cc
     Creating library C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example
  \node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\nod
  e_modules\bufferutil\build\Release\bufferutil.lib and object C:\work\Aurelia-Guides\ag-sampl
  es\aurelia-wizard-form-validation-example\node_modules\browser-sync\node_modules\socket.io\n
  ode_modules\engine.io\node_modules\ws\node_modules\bufferutil\build\Release\bufferutil.exp
  Generating code
  Finished generating code
  bufferutil.vcxproj -> C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-examp
  le\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\n
  ode_modules\bufferutil\build\Release\\bufferutil.node
/


> utf-8-validate@1.1.0 install C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild

-
C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate {git}
{lamb} if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  validation.cc
     Creating library C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example
  \node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\nod
  e_modules\utf-8-validate\build\Release\validation.lib and object C:\work\Aurelia-Guides\ag-s
  amples\aurelia-wizard-form-validation-example\node_modules\browser-sync\node_modules\socket.
  io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate\build\Release\validati
  on.exp
  Generating code
  Finished generating code
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(607,5): err or MSB6003: The specified task executable "link.exe" could not be run. The specified path, fil e name, or both are too long. The fully qualified file name must be less than 260 characters,
and the directory name must be less than 248 characters. [C:\work\Aurelia-Guides\ag-samples\au relia-wizard-form-validation-example\node_modules\browser-sync\node_modules\socket.io\node_mod ules\engine.io\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
\


> utf-8-validate@1.1.0 install C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild


C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate {git}
{lamb} if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(5039,39): erro r MSB4023: Cannot evaluate the item metadata "%(FullPath)". The item metadata "%(FullPath)" ca nnot be applied to the path "Release\obj\validation\validation.node". C:\work\Aurelia-Guides\a g-samples\aurelia-wizard-form-validation-example\node_modules\browser-sync\node_modules\socket .io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\u tf-8-validate\build\Release\obj\validation\validation.node [C:\work\Aurelia-Guides\ag-samples\ aurelia-wizard-form-validation-example\node_modules\browser-sync\node_modules\socket.io\node_m odules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-valid ate\build\validation.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0


> bufferutil@1.1.0 install C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild


C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil {git}
{lamb} if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(5039,39): erro r MSB4023: Cannot evaluate the item metadata "%(FullPath)". The item metadata "%(FullPath)" ca nnot be applied to the path "Release\obj\bufferutil\bufferutil.node". C:\work\Aurelia-Guides\a g-samples\aurelia-wizard-form-validation-example\node_modules\browser-sync\node_modules\socket .io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\b ufferutil\build\Release\obj\bufferutil\bufferutil.node [C:\work\Aurelia-Guides\ag-samples\aure lia-wizard-form-validation-example\node_modules\browser-sync\node_modules\socket.io\node_modul es\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil\buil d\bufferutil.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
ERR! cwd C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm WARN optional dep failed, continuing bufferutil@1.1.0
npm WARN deprecated jsonstream@1.0.3: use JSONStream instead
-


> ws@0.4.32 install C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws {git}
{lamb} if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bufferutil.cc
     Creating library C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example
  \node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\bui
  ld\Release\bufferutil.lib and object C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-v
  alidation-example\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\no
  de_modules\ws\build\Release\bufferutil.exp
  Generating code
  Finished generating code
  bufferutil.vcxproj -> C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-examp
  le\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\b
  uild\Release\\bufferutil.node
  validation.cc
     Creating library C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example
  \node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\bui
  ld\Release\validation.lib and object C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-v
  alidation-example\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\no
  de_modules\ws\build\Release\validation.exp
  Generating code
  Finished generating code
  validation.vcxproj -> C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-examp
  le\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\b
  uild\Release\\validation.node
npm WARN prefer global jshint@2.8.0 should be installed with -g
/
> karma-jasmine-jquery@0.1.1 postinstall C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\karma-jasmine-jquery
> node install.js

\
> bufferutil@1.1.0 install C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\gulp-protractor\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild


C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\gulp-protractor\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil {git}
{lamb} if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(308,5): erro r MSB3491: Could not write lines to file "Release\obj\bufferutil\bufferutil.tlog\bufferutil.la stbuildstate". The specified path, file name, or both are too long. The fully qualified file n ame must be less than 260 characters, and the directory name must be less than 248 characters.  [C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\gulp-p rotractor\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules \bufferutil\build\bufferutil.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\gulp-protractor\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok

> utf-8-validate@1.1.0 install C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\gulp-protractor\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild


C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\gulp-protractor\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\utf-8-validate {git}
{lamb} if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(308,5): erro r MSB3491: Could not write lines to file "Release\obj\validation\validation.tlog\validation.la stbuildstate". The specified path, file name, or both are too long. The fully qualified file n ame must be less than 260 characters, and the directory name must be less than 248 characters.  [C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\gulp-p rotractor\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules \utf-8-validate\build\validation.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\gulp-protractor\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.1.0
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! path C:\Users\Nikolaj\AppData\Roaming\npm-cache\array-differ\1.0.0\package\package.json
npm ERR! code EPERM
npm ERR! errno -4048

npm ERR! Error: EPERM, rename 'C:\Users\Nikolaj\AppData\Roaming\npm-cache\array-differ\1.0.0\package\package.json'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM, rename 'C:\Users\Nikolaj\AppData\Roaming\npm-cache\array-differ\1.0.0\package\package.json']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   path: 'C:\\Users\\Nikolaj\\AppData\\Roaming\\npm-cache\\array-differ\\1.0.0\\package\\package.json',
npm ERR!   parent: 'gulp-util' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\npm-debug.log
```

**Comment by adriatic** [comment]
Note that I am always running npm / jspm as adminstrator

**Comment by adriatic** [comment]
this is the list of node_modules folder:

![image](https://cloud.githubusercontent.com/assets/2712405/9837839/b492f5cc-5a19-11e5-8c8e-e103a0dbc2a2.png)

**Comment by adriatic** [comment]
and here is the relevant section of the package.json document
```
  "dependencies": {
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "errorhandler": "^1.1.1",
    "loopback": "^2.19.1",
    "loopback-boot": "^2.8.2",
    "loopback-datasource-juggler": "^2.35.3",
    "serve-favicon": "^2.0.1"
  },
  "optionalDependencies": {},
  "devDependencies": {
    "aurelia-bundler": "^0.1.6",
    "aurelia-cli": "^0.2.1",
    "aurelia-tools": "^0.1.10",
    "babel-eslint": "^4.1.0",
    "browser-sync": "^2.8.2",
    "conventional-changelog": "^0.2.1",
    "del": "^1.2.0",
    "eslint": "^1.2.1",
    "gulp": "^3.9.0",
```

clearly indicating that the ``aurelia-bundler`` did not get installed. So, I will delete the node_modules folder and run it again to eliminate the chance of some "transient error" and if I get the same result, I will add aurelia-bundler with jspm interactively

**Comment by stevies** [comment]
Ah. If npm install does not complete without errors, then you are a bit stuffed,  I think I recall that I had to install Visual Studio or something to get the required system libs on my Windows machines.  And I have found that I sometimes have to  run npm install a few times on a new project to get it to load without errors.

You seem  to have gulp.  But are missing aurelia-bundler.

Here's my node_modules.

    Directory: C:\Users\steve\WebstormProjects\aurelia-wizard-form-validation-example\node_modules


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       12/09/2015     18:09                .bin
d-----       12/09/2015     18:00                aurelia-bundler
d-----       12/09/2015     18:03                aurelia-cli
d-----       12/09/2015     17:59                aurelia-tools
d-----       12/09/2015     18:00                babel-eslint
d-----       12/09/2015     18:03                browser-sync
d-----       12/09/2015     17:59                compression
d-----       12/09/2015     18:00                conventional-changelog
d-----       12/09/2015     17:59                cors
d-----       12/09/2015     17:59                del
d-----       12/09/2015     17:59                errorhandler
d-----       12/09/2015     18:03                eslint
d-----       12/09/2015     17:59                gulp
d-----       12/09/2015     18:00                gulp-babel
d-----       12/09/2015     17:59                gulp-bump
d-----       12/09/2015     17:59                gulp-changed
d-----       12/09/2015     17:59                gulp-eslint
d-----       12/09/2015     17:59                gulp-expect-file
d-----       12/09/2015     17:59                gulp-jshint
d-----       12/09/2015     17:59                gulp-less
d-----       12/09/2015     17:59                gulp-open
d-----       12/09/2015     17:59                gulp-plumber
d-----       12/09/2015     18:00                gulp-protractor
d-----       12/09/2015     17:59                gulp-sourcemaps
d-----       12/09/2015     17:59                gulp-uglify
d-----       12/09/2015     18:02                gulp-yuidoc
d-----       12/09/2015     18:00                isparta
d-----       12/09/2015     18:01                istanbul
d-----       12/09/2015     18:00                jasmine-core
d-----       12/09/2015     18:05                jshint
d-----       12/09/2015     17:59                jshint-stylish
d-----       12/09/2015     18:01                jspm
d-----       12/09/2015     18:00                karma
d-----       12/09/2015     18:00                karma-babel-preprocessor
d-----       12/09/2015     17:59                karma-chrome-launcher
d-----       12/09/2015     17:59                karma-coverage
d-----       12/09/2015     17:59                karma-jasmine
d-----       12/09/2015     17:59                karma-jasmine-ajax
d-----       12/09/2015     17:59                karma-jasmine-html-reporter
d-----       12/09/2015     18:08                karma-jasmine-jquery
d-----       12/09/2015     17:59                karma-jasmine-matchers
d-----       12/09/2015     17:59                karma-jspm
d-----       12/09/2015     17:59                karma-phantomjs-launcher
d-----       12/09/2015     17:59                karma-sinon
d-----       12/09/2015     17:59                karma-source-map-support
d-----       12/09/2015     17:59                karma-spec-reporter
d-----       12/09/2015     17:59                karma-story-reporter
d-----       12/09/2015     17:59                less-plugin-clean-css
d-----       12/09/2015     18:04                loopback
d-----       12/09/2015     18:00                loopback-boot
d-----       12/09/2015     18:04                loopback-datasource-juggler
d-----       12/09/2015     17:59                object.assign
d-----       12/09/2015     17:59                phantomjs
d-----       12/09/2015     17:59                require-dir
d-----       12/09/2015     17:59                run-sequence
d-----       12/09/2015     17:59                serve-favicon
d-----       12/09/2015     18:01                sinon
d-----       12/09/2015     17:59                vinyl-paths
d-----       12/09/2015     17:59                yargs

**Comment by adriatic** [comment]
Our posts crossed :-) 

I have no problems resolving this issue - and when I do, I will state it here, for the chance you might need it later

**Comment by stevies** [comment]
Note my comments on the readme.  When you do get it all installed, you'll still have a problem running it unless you patch the current index.js file in /app/jspm_packages/github/aurelia/validation@0.3.0.  That should get fixed soon when the next version of aurelia-validation get released (the fix is in master now).

**Comment by adriatic** [comment]
I am aware of that and already patched the relevant file (which is now gone, as I deleted the whole darn thing)

**Comment by adriatic** [comment]
The problem with that node-gyp is that one of its dependencies makes a specific request to the VC++ DLL (from VS 2008 if I remember it well) and that version is likely gone from my machine. However, this problem results with the use of JavaScript version of some bufferutil piece instead of running the native code

**Comment by adriatic** [comment]
Here is a very hopeful article on fixing nod-gyp https://www.robertkehoe.com/2015/03/fix-node-gyp-rebuild-error-on-windows/

**Comment by adriatic** [comment]
Got past npm problems (in the second attempt to run ``npm install`` everything went fine - meaning that we really have some transient problems with npm). Started the ``node server.js`` in a different command window and pointed the browser to localhost:3000:

```
404 Error: Cannot GET /
   at raiseUrlNotFoundError (C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\loopback\server\middleware\url-not-found.js:15:17)
   at Layer.handle [as handle_request] (C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\loopback\node_modules\express\lib\router\layer.js:95:5)
   at trim_prefix (C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\loopback\node_modules\express\lib\router\index.js:312:13)
   at C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\loopback\node_modules\express\lib\router\index.js:280:7
   at Function.process_params (C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\loopback\node_modules\express\lib\router\index.js:330:12)
   at next (C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\loopback\node_modules\express\lib\router\index.js:271:10)
   at SendStream.error (C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\loopback\node_modules\express\node_modules\serve-static\index.js:120:7)
   at SendStream.emit (events.js:107:17)
   at SendStream.error (C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\loopback\node_modules\express\node_modules\send\index.js:245:17)
   at SendStream.onStatError (C:\work\Aurelia-Guides\ag-samples\aurelia-wizard-form-validation-example\node_modules\loopback\node_modules\express\node_modules\send\index.js:356:12)
```

Now, this is your turn :-)

**Comment by stevies** [comment]
Did you run 'gulp bundle'?  What is in your /deploy directory?  

I will try to pull down a new clean copy from github and build and run it.  Sometimes you miss things running in an IDE, and this whole thing was hacked together quickly and I have skipped all testing.

**Comment by adriatic** [comment]
Oh, I assumed that gulp watch will run gulp bundle as a subtask. Ok, let me have lunch and I will get this done

**Comment by stevies** [comment]
My thought was that the bundle task is separate because you really only want to do that when you know that you have a stable, working version - ready to deploy (at least to an integration / test server if not production).  Watch is looking at the files as you develop, and is continually building (and resetting browser-sync).  That is fine during development - when you can see instant changes on  http://localhost:9000 - but bundling is quite slow, so not something you want running all the time.

**Comment by adriatic** [comment]
Isolating gulp bundle is certainly a good move. Trying to run this step alone I run into the problem: I do not know how to apply the patch for ``app/jspm_packages/github/aurelia/validation@0.3.0/index.js``. It is most likely a git command but I do not want to take a chance of guessing, so please paste me a copy of right version of that file here.

**Comment by stevies** [comment]
```
/* */
define(['exports', './validation/validation-config', './validation/validation', './validation/utilities',
  './validation/validation-locale', './validation/validation-result', './validation/validation-rules',
  './validation/validate-custom-attribute', './validation/validate-custom-attribute-view-strategy',
  './validation/decorators','./validation/validation-group'], function (exports, _validationValidationConfig,
                                                                        _validationValidation, _validationUtilities, _validationValidationLocale, _validationValidationResult,
                                                                        _validationValidationRules, _validationValidateCustomAttribute, _validationValidateCustomAttributeViewStrategy,
                                                                        _validationDecorators, _validationGroup) {
  'use strict';

  exports.__esModule = true;
  exports.configure = configure;

  function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } else { var newObj = {}; if (obj != null) { for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) newObj[key] = obj[key]; } } newObj['default'] = obj; return newObj; } }

  function _defaults(obj, defaults) { var keys = Object.getOwnPropertyNames(defaults); for (var i = 0; i < keys.length; i++) { var key = keys[i]; var value = Object.getOwnPropertyDescriptor(defaults, key); if (value && value.configurable && obj[key] === undefined) { Object.defineProperty(obj, key, value); } } return obj; }

  exports.Utilities = _validationUtilities.Utilities;
  exports.ValidationConfig = _validationValidationConfig.ValidationConfig;
  exports.ValidationLocale = _validationValidationLocale.ValidationLocale;

  _defaults(exports, _interopRequireWildcard(_validationValidationResult));

  _defaults(exports, _interopRequireWildcard(_validationValidationRules));

  exports.Validation = _validationValidation.Validation;
  exports.ValidateCustomAttribute = _validationValidateCustomAttribute.ValidateCustomAttribute;
  exports.ValidateCustomAttributeViewStrategy = _validationValidateCustomAttributeViewStrategy.ValidateCustomAttributeViewStrategy;
  exports.ValidateCustomAttributeViewStrategyBase = _validationValidateCustomAttributeViewStrategy.ValidateCustomAttributeViewStrategyBase;
  exports.ValidationGroup = _validationGroup.ValidationGroup;

  exports.ensure = _validationDecorators.ensure;

  function configure(aurelia, configCallback) {

    aurelia.globalResources('./validation/validate-custom-attribute');
    if (configCallback !== undefined && typeof configCallback === 'function') {
      configCallback(_validationValidation.Validation.defaults);
    }
    aurelia.singleton(_validationValidationConfig.ValidationConfig, _validationValidation.Validation.defaults);
    return _validationValidation.Validation.defaults.locale();
  }
});
```

**Comment by adriatic** [comment]
Amazing speed - and I have to ask: where are you?

**Comment by stevies** [comment]
Scotland

**Comment by adriatic** [comment]
One of my favorite places anywhere - had some wonderful friends in Edinburgh that made me feel like at home. Scots are great people, very different from englishman

**You have yet to see what all will I do with this sample**

![image](https://cloud.githubusercontent.com/assets/2712405/9838817/815773d4-5a34-11e5-8d95-a8c421e1a6cd.png)

**Comment by adriatic** [comment]
Just love the way you think and write code

**Comment by stevies** [comment]
Thanks.  I can't take any credit for the wizard - that was PWKad.  As was the idea behind the more complex 2-field validation.  Aurelia makes it quite easy to write more elegant and self-explanatory code.

**Comment by adriatic** [comment]
I saw your "transfer" of credit to PWKad, that will be of course on full display in the article I am about to write. However, I would give you a lot of credit for the application structure as well
